### PR TITLE
Workaround LG-related menu issues, pt. 2

### LINKED ISSUE #2444: Remaining material crashes
Still seeing this for the "Torque (E6710)"

`````
java.lang.NullPointerException
at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:440)
at com.android.internal.policy.impl.PhoneWindow.onKeyDownPanel(PhoneWindow.java:772)
at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1437)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1831)
at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3577)
at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3547)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2797)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4774)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
at dalvik.system.NativeStart.main(Native Method)
``````

### PR DESCRIPTION
**Pull request by mcginty**
Proposal for temporary assurances that people can use the app: loosen criteria for the keycode workaround, and at the same time force the "three dots" overflow menu regardless of hardware on devices running  Android 4.x ROMs which seem to be the problem zone.

Fixes #2444

### CODE REVIEW

**Comment by moxie0** [comment]
Let's only do this for LGE and that Torque device. Using reflection to access private fields is bound to cause problems, so we should try to limit its use to as few devices as possible.

**Comment by mcginty** [comment]
Do you have any `Build` statics information for me to filter that Torque device?

**Comment by moxie0** [comment]
According https://support.google.com/googleplay/answer/1727131?hl=en-GB Build.DEVICE is E6710

**Comment by mcginty** [comment]
updated

File: src/org/thoughtcrime/securesms/BaseActionBarActivity.java [hunk 1]
```diff
@@ -19,4 +39,20 @@ public boolean onKeyUp(int keyCode, @NonNull KeyEvent event) {
...
   }
+
+  /**
+   * Modified from: http://stackoverflow.com/a/13098824
+   */
+  private void forceOverflowMenu() {
+    try {
+      ViewConfiguration config       = ViewConfiguration.get(this);
+      Field             menuKeyField = ViewConfiguration.class.getDeclaredField("sHasPermanentMenuKey");
+      if(menuKeyField != null) {
```
Comment (agrajaghh) [inline src/org/thoughtcrime/securesms/BaseActionBarActivity.java]: super nitpick: space

File: src/org/thoughtcrime/securesms/BaseActionBarActivity.java [hunk 2]
```diff
@@ -1,11 +1,31 @@
...
 
 
 public abstract class BaseActionBarActivity extends ActionBarActivity {
+  private static final String TAG = BaseActionBarActivity.class.getSimpleName();
+
+  @Override
+  protected void onCreate(Bundle savedInstanceState) {
+    if (VERSION.SDK_INT <= VERSION_CODES.JELLY_BEAN &&
+        VERSION.SDK_INT  > VERSION_CODES.GINGERBREAD_MR1 &&
+        ("LGE".equalsIgnoreCase(Build.MANUFACTURER) || "E6710".equalsIgnoreCase(Build.DEVICE))) {
```
Comment (moxie0) [inline src/org/thoughtcrime/securesms/BaseActionBarActivity.java]: Why isn't this in isKeyCodeWorkaroundRequired?

**Comment by mcginty** [comment]
(updated)

File: src/org/thoughtcrime/securesms/BaseActivity.java [hunk 3]
```diff
@@ -8,21 +10,21 @@
...
     return super.onKeyUp(keyCode, event);
   }
 
-  public static boolean isKeyCodeWorkaroundRequired(int keyCode) {
-    return (keyCode == KeyEvent.KEYCODE_MENU) &&
-           (Build.VERSION.SDK_INT == 16)      &&
-           ("LGE".equalsIgnoreCase(Build.MANUFACTURER));
+  public static boolean isMenuWorkaroundRequired() {
+    return Build.VERSION.SDK_INT <= VERSION_CODES.JELLY_BEAN &&
+           VERSION.SDK_INT  > VERSION_CODES.GINGERBREAD_MR1  &&
```
Comment (moxie0) [inline src/org/thoughtcrime/securesms/BaseActivity.java]: Just to make sure, are VERSION_CODES.GINGERBREAD and GINGERBREAD_MR1 not affected by this?  Just HC, ICS, and JB?

Comment (mcginty) [inline src/org/thoughtcrime/securesms/BaseActivity.java]: From the issue, it sounded like ICS and JB, but HC is less common compared to 4.x an 2.3.x, so I included it as precautionary if it didn't get reported.

These are based on reports from other people's Play store consoles though, so let me know if you ended up seeing one that was GB or KK

Comment (moxie0) [inline src/org/thoughtcrime/securesms/BaseActivity.java]: Cool, lgtm.  You can optionally make Build.VERSION.SDK_INT vs VERSION.SDK_INT consistent if you'd like.  =)
